version: "3.8"
services:
  server:
    build: ./server
    container_name: server_container
    ports:
      - '1337:1337'
    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - mongodb
  client:
    build: ./client
    container_name: client_container
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:
